name: Build CMake project

defaults:
  run:
    shell: pwsh

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # TODO: USE PRESETS!!!
        configuration: [ "Debug", "Release" ]
        os: [ "windows-latest", "ubuntu-latest" ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: "UAssetAPI-DNNE/packages.lock.json"

      - name: Display dotnet version
        run: dotnet --version

      - run: dotnet restore

      - name: Setup MSVC dev env
        uses: ilammy/msvc-dev-cmd@v1

      # TODO: remove later.
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          find ~ -type f -executable -name "*platform.c" 2>/dev/null || true

      # TODO: maybe this is a bit lazy?
      - name: Install latest CMake
        run: pip install --upgrade cmake

      - run: cmake --version

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo "DOTNET_BUILD_EXTRA_ARGS=--no-restore" >> $env:GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake 
            -B ${{github.workspace}}/build 
            -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
            -DUASSETAPI_DNNE_DOTNET_BUILD_EXTRA_ARGS=${{ env.DOTNET_BUILD_EXTRA_ARGS }}

      # TODO: remove later.
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          find ~ -type f -executable -name "*platform.c" 2>/dev/null || true

      - run: |
          dotnet nuget locals all --list --force-english-output
          dotnet list package --include-transitive

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.configuration }}

      # TODO: remove later.
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          find ~ -type f -executable -name "*platform.c" 2>/dev/null || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UAssetAPI-DNNE-cmake-build-${{ matrix.os }}-${{ matrix.configuration }}
          path: ${{github.workspace}}/build
