name: Build CMake project

defaults:
  run:
    shell: pwsh

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # TODO: presets?
        os: [ "windows-latest", "ubuntu-latest" ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: "UAssetAPI-DNNE/packages.lock.json"

      - name: Display dotnet version
        run: dotnet --version

      - run: cmake --version
